---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
  tag: "tags"
baseurl: "http://gouyang.github.io"
title: "Guohua"
builddrafts: true

params:
  Description: "细看风景，慢慢忙活"
menu:
  main:
    - Name: "Linux"
      Pre: "<i class='fa fa-heart'></i>"
      Weight: -110
      Identifier: "linux"
      Url: "/linux/"
    - Name: "Go"
      Pre: "<i class='fa fa-road'></i>"
      Weight: -100
      Identifier: "go"
      Url: "/go/"
    - Name: "Python"
      Pre: "<i class='fa fa-road'></i>"
      Weight: -100
      Identifier: "python"
      Url: "/python/"
    - Name: "About"
      Pre: "<i class='fa fa-road'></i>"
      Weight: -100
      Identifier: "about"
      Url: "/about/"

noTimes: false 
paginate: 10
paginatePath: "page"
...
